# Generated by Django 5.1.5 on 2025-01-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
